version: '3.8'

networks:
  laravel:
    driver: bridge

services:

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: iianoexpress
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  php:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php
    ports:
      - "8080:80" 
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

volumes:
  db_data:
